"""
This replaces the default script generated by distlib and pip to one that does
not import the 're' module.

Windows is cursed to always end up importing slow modules as soon as you work
with paths so this is only useful outside of windows for a small performance
boost.
"""

import sys
import os.path

from distlib.scripts import ScriptMaker

from . import LAUNCHER_NAME

NEW_SCRIPT_TEMPLATE = r'''# -*- coding: utf-8 -*-
import sys
from %(module)s import %(import_name)s
if __name__ == '__main__':
    if sys.argv[0].endswith('.exe'):
        sys.argv[0] = sys.argv[0][:-4]
    elif sys.argv[0].endswith('-script.pyw'):
        sys.argv[0] = sys.argv[0][:-11]
    sys.exit(%(func)s())
'''


def hack_slow_launcher():
    maker = ScriptMaker(
        source_dir=None,
        target_dir=os.path.dirname(sys.executable),
    )
    maker.script_template = NEW_SCRIPT_TEMPLATE

    # Copy pip settings
    maker.clobber = True
    maker.variants = {""}
    maker.set_mode = True

    maker.make(f"{LAUNCHER_NAME} = {LAUNCHER_NAME}:main")

    print("Launcher patched")
