"""
By default the entrypoint generated by distlib uses a regex to replace some basic strings.
This relies on importing `re` and is slow.
If `re` is detected as imported by snakerun it will attempt to find the script path
and replace this import with a simpler check
"""
import sys
import os

from . import LAUNCHER_NAME

def fix_slow_entrypoint():


    re_func = r"sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])"
    new_func = (
        "if sys.argv[0].endswith('-script.pyw'):\n"
        "    sys.argv[0] = sys.argv[0][:-11]\n"
        "elif sys.argv[0].endswith('.exe'):\n"
        "    sys.argv[0] = sys.argv[0][:-4]"
    )

